Feature/bind mount pacman cache
Finkregh/archstrap pull request #10
Opened 2020-05-11 21:51 UTC by Finkregh

2020-05-19 17:53 UTC, killermoehre requested changes

2020-05-19 17:53 UTC, killermoehre commented on start-vm.sh
> +  -virtfs local,path=/var/cache/pacman/pkg,mount_tag=host0,security_model=passthrough,id=host0
Instead of running the process as root, how about running qemu as the current user? With [SLIRP](https://wiki.qemu.org/Documentation/Networking#User_Networking_.28SLIRP.29) there is even user mode networking.
Or we leverage this with `libvirt` and qemu:///session

2020-05-19 17:53 UTC, killermoehre commented on bootstrap.sh
> +  # 9.1.: pacman mirrorlist
numbering is off

2020-05-19 17:53 UTC, killermoehre commented on bootstrap.sh
> +    systemd-nspawn -D "$DEST_CHROOT_DIR" -- rankmirrors -n 10 /etc/pacman.d/mirrorlist-de-curated >"$DEST_CHROOT_DIR/etc/pacman.d/mirrorlist"
Instead of `rankmirror` from `pacman-contrib`, why not use `reflector`? It has the fancy stuff inbuilt, like ranking and country select.

2020-05-19 17:53 UTC, killermoehre commented on bootstrap.sh
> +    *\ Intel\ *) pacstrap $DEST_CHROOT_DIR xf86-video-intel ;;
The intel driver is horrible. The general suggestion is to use the modesetting driver (included in `xorg-server`),

2020-05-19 17:53 UTC, killermoehre commented on bootstrap.sh
> +    pacstrap $DEST_CHROOT_DIR lightdm
Only installing `lightdm` won't lead to any desktop environment, so the user would see nothing.
Also without a actual user created `lightdm` can't even be used properly, as you don't want to login as `root`.

2020-05-19 17:53 UTC, killermoehre commented on bootstrap.sh
> +  } | dialog --progressbox "Installing GFX drivers" ${_termlines} ${_termwidth}
```bash
# as there are no multidimensional arrays in bash, we need two helper arrays
declare -a dri_cards=()
declare -A dri_vendor=()
declare -A dri_model=()
for dri_card in /dev/dri/card*; do
    dri_card_name="${dri_card##*/}"
    dri_cards+=( "$dri_card_name" )
    sys_path="$(udevadm info --query=path "$dri_card")"
    # source the variables from udev to be available in the current context
    . <(udevadm info --query=property --export "--path=${sys_path}/device")
    dri_vendor+=( ["$dri_card_name"]="$ID_VENDOR_FROM_DATABASE" )
    dri_model+=( ["$dri_card_name"]="$ID_MODEL_FROM_DATABASE" )
done
card_overview_text='Following DRI cards were found:

'
for dri_card in "${dri_cards[@]}"; do
    card_overview_text+="$dri_card: ${dri_vendor[$dri_card]} ${dri_model[$dri_card]}
"
done
card_overview_text+='
See <https://wiki.archlinux.org/index.php/Xorg#Driver_installation> for the suggested driver.

Which driver should be installed?'
exec 3>&1
_driver_to_install="$(dialog --menu "$(printf '%s' "$card_overview_text")" ${_termlines} ${_termwidth} 0 'xf86-video-nouveau' 'Nvidia®' 'xf86-video-ati' 'ATI®' 'xf86-video-amdgpu' 'AMD®' 2>&1 1>&3)"
exec 3>&-
pacstrap "$DEST_CHROOT_DIR" "$_driver_to_install"
```
or something like this

2020-05-20 21:46 UTC, Finkregh commented on start-vm.sh
> +  -virtfs local,path=/var/cache/pacman/pkg,mount_tag=host0,security_model=passthrough,id=host0
root is needed for virtfs,sec-model=pass.
feel free to wrap with with libvirt, for now it worked quite well :P

2020-05-20 21:48 UTC, Finkregh commented on bootstrap.sh
> +    systemd-nspawn -D "$DEST_CHROOT_DIR" -- rankmirrors -n 10 /etc/pacman.d/mirrorlist-de-curated >"$DEST_CHROOT_DIR/etc/pacman.d/mirrorlist"
this is a curated list of "trusted" mirrors which i then sort by speed or whatnot. We may also switch to reflector 🤷‍♀️

2020-05-20 21:50 UTC, Finkregh commented on bootstrap.sh
> +    pacstrap $DEST_CHROOT_DIR lightdm
well, lets do that in another PR then? just use this as base and extend from there, then we dont get even more stuff in here?

2020-07-10 19:46 UTC, Finkregh commented on bootstrap.sh
> +  } | dialog --progressbox "Installing GFX drivers" ${_termlines} ${_termwidth}
in another PR then...

2020-07-10 19:46 UTC, merged